### ISSUE TITLE
Create three user types

### ISSUE THREAD

**Issue by DonGiovanni83** [eseTeam2/ese2018-team2#27]
**Is your feature request related to a problem? Please describe.**
users should be classified according to their role. Students, company members, and admins should have their own toolsets and dashboards.

**Describe the solution you'd like**
Our database model has to be updated in a way such that users with specific roles can be identified. What the required tools and how the dashboards for each role should look like has to be discussed and planned further before implementation.

**Comment by ioboi** [comment]
With the siteAdmin flag on the user model, it is clear, that a user is a system administrator.

If a user is added to an organization, the user is automatically an organizational user.
I think the organization needs to have a relationship to user.

**Comment by DonGiovanni83** [comment]
Working on this issue on #42
