### ISSUE TITLE
ManyToMany-Join results in unknown relation

### ISSUE THREAD

**Issue by DonGiovanni83** [eseTeam2/ese2018-team2#28]
**Describe the bug**
leftJoin of User and Jobs to get the liked jobs on attributes user.likedJobs and job.userLiked gives the following error:
"relation \"users_liked_jobs_jobs\" does not exist",

**To Reproduce**
1. Go to http://localhost:4000/
2. Execute:
`query allJobs{
  jobs{
    id
    title
  }
}`
3. Select a jobId and Execute both mutations with the chossen jobId
`
mutation loginAndLike{
  login(email: "admin@example.com", pw: "123456")
  likeJob(jobId: "87ecf5dd-e471-46f2-89bc-0738f91f285d")
}
`
4. likeJob mutation should result with the mentioned error

**Expected behavior**
likeJob should make an Entry on the User Job join on attributes user.likedJobs and job.usersLiked

**Comment by ioboi** [comment]
You should regenerate the database patch for the schema. You can do this once #29 is fixed.

**Comment by DonGiovanni83** [comment]
issue fixed (since Commit 81e368984a0b5bb0cfc307ceb09b14e0a0acd9f4)

**Comment by ioboi** [comment]
#29
